import { NextPage } from "../data";
import { CustomErrorComponent } from "../components";
import { CUSTOM_ERROR_PROPS } from "../data";

const CustomError: NextPage<CUSTOM_ERROR_PROPS> = ({ statusCode }) => {
  return <CustomErrorComponent statusCode={statusCode} />;
};

CustomError.getInitialProps = ({ res, err }) => {
  //   First we will check the status code returned by default from Next and then check if there is a custom code generated by our application, if so we will set this code as our response status code
  const currentStatusCode = res?.statusCode || 500;
  const throwedStatusCode = err?.statusCode;

  const statusCode = throwedStatusCode || currentStatusCode;

  if (res) {
    // Here is where the magic happens
    res.statusCode = statusCode;
  }

  return { statusCode };
};

export default CustomError;
